db.getCollection('templates').aggregate([
    {
        "$match":{"form_id":formDetails.formId,"domain_name":formDetails.domainName,"user_token":userDetails.userToken}
    },
    {
        "$lookup":{
            "from":"forms",
            "localField":"form_id",
            "foreignField":"form_id",
            "as":"form"
        }
    },
    {
        "$addFields":{
            "form":{
                "$filter":{
                    "input":"$form",
                    "as":"form",
                    "cond":{
                        "$and":[
                            {$eq:["$$form.form_id",formDetails.formId]},
                            {$eq:["$$form.domain_name",formDetails.domainName]},
                            {$eq:["$$form.user_token",userDetails.userToken]}
                        ]
                    }
                }
            }
        }
    },
    {
        "$addFields":{
            "send_submission_reply":{"$arrayElemAt":["$form.send_submission_reply",0]},
            "form_data_feilds":{"$arrayElemAt":["$form.form_data_feilds",0]}
        }
    },
    {
        "$project":{
            "form":0
        }
    }
])
